### ISSUE TITLE
Encoding of local characters in folder names

### ISSUE THREAD

**Issue by RasmusMalver** [arjanarcheologie/mmy#5]
Nice plugin. Slight issue: I use `ø` and `æ` in folder names, which is rendered as `&APg-` and `&AOY-`. The words in the screenshots are `køb` and `hjælp`. 

![Screenshot 2024-04-01 at 23 32 09](https://github.com/arjanarcheologie/mmy/assets/1069447/09ac8b83-8008-44ff-bd68-083147f7fb66)
![Screenshot 2024-04-01 at 23 32 05](https://github.com/arjanarcheologie/mmy/assets/1069447/4f561fa4-aea6-4f79-8054-1e4148726c0a)

**Comment by arjanarcheologie** [comment]
I updated the plugin (1.10) so it uses the correct display string. Hope it works now.

**Comment by RasmusMalver** [comment]
> I updated the plugin (1.10) so it uses the correct display string. Hope it works now.

It's fixed!
